language: go

branches:
  only:
  - master
  - /^v.*$/
  - /^issue-\d+/

go:
  - "1.13.7"

sudo: false

services:
  - docker

install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1
  - make dep

script:
  # Code coverage and testing
  - make lint
  - make coverage
  - bash <(curl -s https://codecov.io/bash)
  - bash ./travis.sh || travis_terminate 1
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - ./bin/prometheus-webexteams-darwin-amd64
    - ./bin/prometheus-webexteams-linux-amd64
    - ./bin/shasum256.txt
    - ./default-message-card.tmpl
  skip_cleanup: true
  on:
    tags: true

