---
apiVersion: v1
kind: Secret
metadata:
 name: {{ template "app.name" . }}-card-template
data:
{{- if .Values.customCardTemplate }}
    {{- range $key, $val := .Values.customCardTemplate }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
